### ISSUE TITLE
GUI 1.0.0 ERROR message

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge-gui#71] opened 2016-07-21 00:03 UTC
When i try to stop storjshare after its already running by clicking on the green start button, the program "hangs" , when i click multiple times while it hangs, it gives this error message:
After that i get a white screen.
![2016-07-21](https://cloud.githubusercontent.com/assets/11735738/17007149/2a3bf8f0-4ede-11e6-8c55-6bca7cbe3fdc.png)

**Comment by super3** [comment] 2016-07-21 18:44
@MeijeSibbel This is a duplicate of my issue here: https://github.com/Storj/storjshare-gui/issues/290
Closing since mine includes more detail. You can add a comment and follow from my issue.

**Closed** 2016-07-21 18:44 UTC
